#!/usr/bin/env python3
"""
Top-N ranked chair listings from the SQLite cache, with a clean descriptive
title and optional 1-10 condition score generated by the LLM.

Two surfaces:

  • Python import:   from top_chairs import get_top_chairs
                     listings = get_top_chairs("gd", n=15, min_quantity=50)

  • CLI:             .venv/bin/python top_chairs.py --source gd --n 15
                     .venv/bin/python top_chairs.py --source ps --min-qty 100 --json

The function reads ``state/listings.db`` — it does NOT trigger a scrape.
Refresh data by running ``govdeals_chairs_extraction.py`` or
``public_surplus_automation.py`` (usually via cron / ``run_all.sh``).

Why read from DB instead of ``state/last_alert_*.json``:
the alert JSON was already filtered at the scraper's ``MIN_CHAIR_QUANTITY``
(50). Reading from the DB lets callers choose any threshold at query time.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

import requests
from dateutil import parser as _date_parser
from dateutil.parser import UnknownTimezoneWarning
from dotenv import load_dotenv

# GovDeals end_date strings use "EDT" / "EST" abbreviations. dateutil parses
# them but emits a UnknownTimezoneWarning for each parse — hundreds of those
# per request is pure noise. We don't care about sub-hour precision for the
# "is this auction over" check, so silence it.
warnings.filterwarnings("ignore", category=UnknownTimezoneWarning)

load_dotenv()
load_dotenv(Path(__file__).parent / ".env", override=True)

OLLAMA_BASE_URL = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "gpt-oss:120b-cloud")

# URL patterns identify which site a cached row came from — the asset_id
# column is prefixed "ps:" for Public Surplus and left unprefixed for GovDeals.
_GOVDEALS_URL_FRAG = "govdeals.com"
_PUBLIC_SURPLUS_URL_FRAG = "publicsurplus.com"


Source = Literal["gd", "ps"]


def _price_to_float(p: str | None) -> float:
    """Best-effort price parse for sorting. Returns inf on failure."""
    s = str(p or "")
    digits = "".join(c for c in s if c.isdigit() or c == ".")
    try:
        return float(digits) if digits else float("inf")
    except ValueError:
        return float("inf")


# Defensive upper bound for the quantity filter. Real chair lots above this
# are essentially non-existent; anything that slips through is almost always
# an auction ID or lot number that polluted the regex fallback. Keeps the
# API output from displaying "218,321 chairs" if a pollution regression ever
# lands in the scraper.
_SANE_MAX_QUANTITY = 50_000


# Only quantities produced by the LLM pass are trusted for ranking, the
# MIN_CHAIR_QUANTITY filter, and Telegram alerts. Regex-seeded counts
# (`regex_title` / `regex_fulltext`) and LLM failures (`llm_failed` /
# `llm_missing`) are NOT trusted — the regex path routinely misreads a lot
# number, spec, or model number as a chair count (e.g. a single electric
# wheelchair read as qty=110). Untrusted rows stay in the cache but are
# excluded from the read surface until a successful LLM scrape refreshes them.
# This is the read-side guard for BLACKWHOLE-4; deleting the regex code itself
# is separate cleanup.
TRUSTED_QUANTITY_SOURCE = "llm"


def trusted_quantity(row: dict) -> int | None:
    """Return the row's chair quantity ONLY when it is LLM-verified.

    Returns an int when ``quantity_source == 'llm'`` and ``quantity`` parses,
    else ``None``. Callers should treat ``None`` as "no trustworthy count" —
    exclude it from ranking, the qty filter, and alerts (never coerce to 0
    and then compare, and never fall back to the regex number).
    """
    if (row.get("quantity_source") or "") != TRUSTED_QUANTITY_SOURCE:
        return None
    q = row.get("quantity")
    if q is None:
        return None
    try:
        return int(q)
    except (TypeError, ValueError):
        return None


# Keyword-based vertical classifier. Runs on cached rows at query time —
# no DB column, no LLM call. Medical and dental merge into one bucket.
# See plan: /Users/abdelnasser/.claude/plans/1-combine-medical-and-vectorized-swing.md
_MEDICAL_KEYWORDS: tuple[str, ...] = (
    # patient-facing chairs
    "dental", "dentist", "exam chair", "examination chair",
    "treatment chair", "procedure chair", "phlebotomy", "dialysis",
    "geriatric", "optometry", "ophthalmic", "podiatry", "tattoo",
    "salon chair", "barber chair",
    # equipment riding alongside chairs in medical auctions
    "exam table", "examination table", "treatment couch",
    "stretcher", "gurney", "dental cabinet", "dental cart",
    # brand names that scream medical
    "midmark", "ritter", "pelton & crane", "pelton and crane",
    "takara belmont", "umf medical", "clinton industries",
    "dexta", "smr apex", "lumex", "dntlworks",
)
_BANQUET_KEYWORDS: tuple[str, ...] = (
    "banquet", "stackable", "folding chair", "church chair",
    "event chair", "conference chair",
)


def _classify(title: str | None, description: str | None) -> tuple[str, str]:
    """Return (category, matched_keyword). Category ∈ {medical, banquet, other}."""
    blob = f"{title or ''} {description or ''}".lower()
    for kw in _MEDICAL_KEYWORDS:
        if kw in blob:
            return "medical", kw
    for kw in _BANQUET_KEYWORDS:
        if kw in blob:
            return "banquet", kw
    return "other", ""


# Items that carry a chair-ish word but are NOT banquet/event/stackable
# seating. Keeps the deal-finder focused; mirrors the manual 2026-06-17 purge
# of auction_listings. (Medical exam/dental chairs are handled separately via
# _classify -> "medical" + the INCLUDE_MEDICAL gate, not here.)
_NON_CHAIR_TERMS = (
    "scale", "stool", "ottoman", "pouf", "footrest", "lumbar support",
    "recliner", "filing cabinet", "file cabinet", "pillow", "drafting chair",
)


def _is_non_chair_lot(title: str | None) -> bool:
    """True when a title is clearly not banquet seating despite a chair-ish
    word (e.g. 'Health o Meter Chair Scale', 'Bar Stools Set of 2')."""
    t = (title or "").lower()
    return any(term in t for term in _NON_CHAIR_TERMS)


CATEGORIES = ("banquet", "medical", "other")


def _load_from_cache(source: Source, min_quantity: int) -> list[dict]:
    """Pull listings from ``state/listings.db`` filtered by source + min_qty.

    Sort: quantity DESC, then price ASC (same tiebreak the scrapers use).
    """
    frag = _PUBLIC_SURPLUS_URL_FRAG if source == "ps" else _GOVDEALS_URL_FRAG
    # Use listings_db.connect() so the schema migrations (e.g. pickup_zip)
    # run before we SELECT against columns added in newer versions.
    import listings_db
    conn = listings_db.connect()
    rows = conn.execute(
        """
        SELECT asset_id, link, title, description, quantity,
               quantity_source, quantity_confidence, price, location,
               pickup_zip, contact_email, contact_phone,
               end_date, time_left, image_url, last_seen_at
        FROM listings
        WHERE quantity >= ?
          AND quantity <= ?
          AND quantity_source = ?
          AND link LIKE ?
        ORDER BY quantity DESC
        """,
        (min_quantity, _SANE_MAX_QUANTITY, TRUSTED_QUANTITY_SOURCE, f"%{frag}%"),
    ).fetchall()
    conn.close()
    items = [dict(r) for r in rows]
    items.sort(key=lambda x: (-int(x.get("quantity") or 0), _price_to_float(x.get("price"))))
    return items


def _is_active(row: dict, now: datetime, max_stale_days: int) -> bool:
    """Is this cached listing still a live auction?

    Cache = permanent archive; this function is the read-time filter that
    decides whether a row should appear in the "active listings" UI.

    Two independent signals, both have veto power:

      1. ``end_date`` — if we can parse it and it's in the past, DEAD.
         (GovDeals' "April 20, 2026 07:00 PM EDT" is dateutil-parseable.
          Public Surplus leaves end_date empty, so this check is a no-op
          for PS rows.)
      2. ``last_seen_at`` — if the listing hasn't been re-seen in a scrape
         within ``max_stale_days``, it's probably no longer listed.
         (The scraper only hits active search results; once a listing
         ends, it falls out of search and last_seen_at stops advancing.)

    Returns True (active) only if BOTH checks pass. Returns True when
    data is missing rather than silently dropping rows.
    """
    end = (row.get("end_date") or "").strip()
    if end:
        try:
            dt = _date_parser.parse(end, fuzzy=True)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            if dt < now:
                return False
        except (ValueError, TypeError, OverflowError):
            pass  # Un-parseable — fall through to last_seen_at check.

    last = (row.get("last_seen_at") or "").strip()
    if last:
        try:
            ls = datetime.fromisoformat(last)
            if ls.tzinfo is None:
                ls = ls.replace(tzinfo=timezone.utc)
            if (now - ls).days > max_stale_days:
                return False
        except (ValueError, TypeError):
            pass

    return True


def _enrich_via_llm(items: list[dict]) -> list[dict]:
    """One batched LLM call: clean title + 1-10 condition score + note.

    Condition scale:
        10      like new / unused
         7-8    decent and functional — normal office wear, fully usable
         5-6    visible wear / stains / scuffs but still usable
         3-4    damaged, needs repair to use
         1-2    unusable / scrap
    Default when description gives no condition signal: 6 (assume usable but
    unverified).
    """
    rows = [
        {
            "i": i,
            "raw_title": (it.get("title") or "")[:300],
            "description": (it.get("description") or "")[:1500],
            "quantity": it.get("quantity"),
        }
        for i, it in enumerate(items)
    ]

    prompt = (
        "You are grading chair auction lots for a reseller. For each row, return\n"
        "THREE fields derived from raw_title + description:\n"
        "\n"
        '  1. "title" — 6-12 words describing WHAT the chairs are: type (stackable,\n'
        "     banquet, office, conference, student, folding, recliner, etc),\n"
        "     color/material if mentioned, key feature (casters, arms, padded).\n"
        "     Do NOT include quantity or auction/seller codes like '(218309 TM)'.\n"
        "     If the lot mixes chairs with other items, lead with the chairs.\n"
        "\n"
        '  2. "condition" — integer 1-10 using this scale:\n'
        "        10    like new, unused\n"
        "        7-8   decent and functional — normal office wear, fully usable\n"
        "        5-6   visible wear / stains / scuffs but still usable\n"
        "        3-4   damaged, broken parts, needs repair to use\n"
        "        1-2   unusable, scrap, parts only\n"
        "     Rely on explicit wording in the description. If the description\n"
        "     gives NO condition signal, return 6 (assume usable but unverified).\n"
        "\n"
        '  3. "condition_note" — 4-10 words quoting the key phrase that drove the\n'
        "     score (e.g. 'signs of wear, sold as-is', 'condition not stated',\n"
        "     'professionally cleaned'). Must be human-readable.\n"
        "\n"
        "Reply with ONLY a JSON array, SAME ORDER as input:\n"
        '[{"i": 0, "title": "Black stackable banquet chairs, padded seat",\n'
        '  "condition": 7, "condition_note": "used, good condition"}]\n\n'
        "INPUT:\n" + json.dumps(rows, ensure_ascii=False)
    )

    r = requests.post(
        f"{OLLAMA_BASE_URL.rstrip('/')}/api/chat",
        json={
            "model": OLLAMA_MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
            "options": {"temperature": 0},
        },
        timeout=300,
    )
    r.raise_for_status()
    text = (r.json().get("message") or {}).get("content", "").strip()
    if text.startswith("```"):
        text = "\n".join(text.split("\n")[1:-1]).strip()
    s, e = text.find("["), text.rfind("]")
    data = json.loads(text[s : e + 1])

    by_i: dict[int, dict] = {}
    for o in data:
        if not isinstance(o, dict) or "i" not in o:
            continue
        try:
            idx = int(o["i"])
        except (TypeError, ValueError):
            continue
        try:
            cond = max(1, min(10, int(o.get("condition", 6))))
        except (TypeError, ValueError):
            cond = 6
        by_i[idx] = {
            "title": str(o.get("title") or "").strip(),
            "condition": cond,
            "condition_note": str(o.get("condition_note") or "").strip(),
        }

    out = []
    for i, it in enumerate(items):
        row = by_i.get(i) or {}
        out.append(
            {
                "title": row.get("title") or it.get("title") or "",
                "condition": row.get("condition", 6),
                "condition_note": row.get("condition_note") or "condition not stated",
            }
        )
    return out


def get_top_chairs(
    source: Source = "gd",
    n: int = 15,
    min_quantity: int = 50,
    include_condition: bool = True,
    active_only: bool = True,
    max_stale_days: int = 2,
    category: str | None = None,
) -> list[dict]:
    """Return the top-``n`` chair listings from the cache.

    Args:
        source: ``"gd"`` (GovDeals) or ``"ps"`` (Public Surplus).
        n: Number of listings to return after filtering.
        min_quantity: Only include listings whose inferred chair count is
            at least this. Default 50.
        include_condition: If True, run the condition-scoring LLM
            (~3-10s for a batch of 15). If False, return raw rows without
            the ``title`` rewrite or ``condition`` fields.
        active_only: If True (default), only return listings whose auction
            has NOT ended and whose row was re-seen by the scraper within
            ``max_stale_days``. Pass False to include expired / historical
            rows — useful for archival queries since the cache keeps every
            listing ever scraped.
        max_stale_days: When ``active_only`` is True, a listing is
            considered inactive if the scraper hasn't re-seen it in this
            many days. Default 2 — aligns with a daily scrape schedule
            plus a 1-day grace window.
        category: Optional ``"banquet"`` / ``"medical"`` / ``"other"``
            filter applied via on-read keyword classifier (no DB column).
            When None (default), all categories returned.

    Returns:
        List of dicts, each containing:
            rank (1-based), quantity, title, raw_title, price, end_date,
            time_left, link, image_url, condition (1-10), condition_note.
        When ``include_condition=False``, ``condition`` / ``condition_note``
        are None.

    The function is read-only — it reads the SQLite cache populated by the
    scrapers. It does NOT trigger a scrape.
    """
    if source not in ("gd", "ps"):
        raise ValueError(f"source must be 'gd' or 'ps', got {source!r}")
    if category is not None and category not in CATEGORIES:
        raise ValueError(f"category must be one of {CATEGORIES} or None, got {category!r}")
    items = _load_from_cache(source, min_quantity=max(1, int(min_quantity)))

    # Classify every loaded row so the category survives into the response
    # even when no filter is applied. Cheap — substring search over ~3k rows.
    for it in items:
        cat, kw = _classify(it.get("title"), it.get("description"))
        it["category"] = cat
        it["category_keyword"] = kw

    if category is not None:
        items = [it for it in items if it["category"] == category]

    if active_only:
        now = datetime.now(timezone.utc)
        items = [it for it in items if _is_active(it, now, max_stale_days)]

    top = items[: max(0, int(n))]
    if not top:
        return []

    enrich = None
    if include_condition:
        try:
            enrich = _enrich_via_llm(top)
        except Exception as e:
            # LLM unreachable / timed out / returned junk. Degrade gracefully
            # so the Auctions UI still shows cached listings instead of a 500.
            print(
                f"[top_chairs] condition LLM unavailable ({e!r}); "
                "falling back to raw titles without condition score",
                file=sys.stderr,
            )
            enrich = None
    if enrich is None:
        enrich = [
            {
                "title": it.get("title") or "",
                "condition": None,
                "condition_note": None,
            }
            for it in top
        ]

    out = []
    for i, (it, en) in enumerate(zip(top, enrich), start=1):
        row = {
            "rank": i,
            "quantity": int(it.get("quantity") or 0),
            "title": en["title"],
            "raw_title": it.get("title") or "",
            "price": it.get("price") or "",
            "end_date": it.get("end_date") or "",
            "time_left": it.get("time_left") or "",
            "link": it.get("link") or "",
            "image_url": it.get("image_url") or "",
            "location": it.get("location") or "",
            "pickup_zip": it.get("pickup_zip") or "",
            "contact_email": it.get("contact_email") or "",
            "contact_phone": it.get("contact_phone") or "",
            "category": it.get("category") or "other",
            "category_keyword": it.get("category_keyword") or "",
        }
        # Always include the keys (None when disabled) so downstream consumers
        # can `it["condition"]` without handling KeyError.
        row["condition"] = en["condition"] if include_condition else None
        row["condition_note"] = en["condition_note"] if include_condition else None
        out.append(row)
    return out


def _print_table(listings: list[dict], source: str) -> None:
    print(
        f"\n{'#':<3} {'Qty':>5}  {'Cond':<5} {'Price':<14} {'Ends':<26}  Title  ·  condition note"
    )
    print("-" * 140)
    for it in listings:
        cond = it.get("condition")
        cond_s = f"{cond:>2}/10" if cond is not None else "  -  "
        end = (it.get("end_date") or it.get("time_left") or "N/A")[:26]
        print(
            f"{it['rank']:<3} {it['quantity']:>5}  {cond_s} "
            f"{(it.get('price') or 'N/A')[:14]:<14} {end:<26}  "
            f"{it['title']}  ·  {it.get('condition_note') or ''}"
        )
    print("\n── Links ──")
    for it in listings:
        print(f"  #{it['rank']:<3} qty={it['quantity']:<5} {it['link']}")
        if it.get("image_url"):
            print(f"        image: {it['image_url']}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", choices=("gd", "ps"), default="gd")
    ap.add_argument("--n", type=int, default=15)
    ap.add_argument("--min-qty", type=int, default=50)
    ap.add_argument("--no-condition", action="store_true", help="skip the condition-scoring LLM")
    ap.add_argument("--include-expired", action="store_true",
                    help="include auctions that have ended or haven't been re-seen recently")
    ap.add_argument("--max-stale-days", type=int, default=2,
                    help="with --include-expired off, drop listings not re-seen in N days (default 2)")
    ap.add_argument("--category", choices=CATEGORIES, default=None,
                    help="filter by on-read keyword classifier (banquet / medical / other)")
    ap.add_argument("--json", action="store_true", help="JSON output on stdout (integration-friendly)")
    args = ap.parse_args()

    if not args.json:
        cat = f" [{args.category}]" if args.category else ""
        print(f"Loading top {args.n} {args.source!r} listings{cat} with quantity ≥ {args.min_qty}…")
    listings = get_top_chairs(
        source=args.source,
        n=args.n,
        min_quantity=args.min_qty,
        include_condition=not args.no_condition,
        active_only=not args.include_expired,
        max_stale_days=args.max_stale_days,
        category=args.category,
    )
    if not listings:
        if args.json:
            json.dump([], sys.stdout)
        else:
            print("No listings matched.")
        return 0

    if args.json:
        json.dump(listings, sys.stdout, ensure_ascii=False, indent=2)
        sys.stdout.write("\n")
    else:
        _print_table(listings, args.source)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
